# This Dockerfile builds the API only.

FROM python:3.9
WORKDIR /app

RUN pip install --upgrade pip

COPY backend/requirements.txt backend/api.py backend/.flaskenv ./
RUN pip install -r ./requirements.txt
#ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]
